//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nop.Plugin.Tax.StrikeIron.TaxDataBasic
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.strikeiron.com", ConfigurationName="TaxDataBasic.TaxDataBasicSoap")]
    public interface TaxDataBasicSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.strikeiron.com/GetTaxRateUS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultArrayOfSIWsStatus))]
        System.Threading.Tasks.Task<TaxDataBasic.GetTaxRateUSResponse> GetTaxRateUSAsync(TaxDataBasic.GetTaxRateUSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.strikeiron.com/GetTaxRateCanada", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultArrayOfSIWsStatus))]
        System.Threading.Tasks.Task<TaxDataBasic.GetTaxRateCanadaResponse> GetTaxRateCanadaAsync(TaxDataBasic.GetTaxRateCanadaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.strikeiron.com/GetStatusCodesForMethod", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultArrayOfSIWsStatus))]
        System.Threading.Tasks.Task<TaxDataBasic.GetStatusCodesForMethodResponse> GetStatusCodesForMethodAsync(TaxDataBasic.GetStatusCodesForMethodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.strikeiron.com/GetStatusCodes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultArrayOfSIWsStatus))]
        System.Threading.Tasks.Task<TaxDataBasic.GetStatusCodesResponse> GetStatusCodesAsync(TaxDataBasic.GetStatusCodesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.strikeiron.com/GetServiceInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultArrayOfSIWsStatus))]
        System.Threading.Tasks.Task<TaxDataBasic.GetServiceInfoResponse> GetServiceInfoAsync(TaxDataBasic.GetServiceInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.strikeiron.com/StrikeIron/TaxDataBasic5/TaxDataBasic/GetRemainingHits", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultArrayOfSIWsStatus))]
        System.Threading.Tasks.Task<TaxDataBasic.GetRemainingHitsResponse> GetRemainingHitsAsync(TaxDataBasic.GetRemainingHitsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.strikeiron.com")]
    public partial class LicenseInfo
    {
        
        private UnregisteredUser unregisteredUserField;
        
        private RegisteredUser registeredUserField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public UnregisteredUser UnregisteredUser
        {
            get
            {
                return this.unregisteredUserField;
            }
            set
            {
                this.unregisteredUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public RegisteredUser RegisteredUser
        {
            get
            {
                return this.registeredUserField;
            }
            set
            {
                this.registeredUserField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.strikeiron.com")]
    public partial class UnregisteredUser
    {
        
        private string emailAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EmailAddress
        {
            get
            {
                return this.emailAddressField;
            }
            set
            {
                this.emailAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
    public partial class ServiceInfoRecord
    {
        
        private string infoKeyField;
        
        private string infoValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string InfoKey
        {
            get
            {
                return this.infoKeyField;
            }
            set
            {
                this.infoKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string InfoValue
        {
            get
            {
                return this.infoValueField;
            }
            set
            {
                this.infoValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
    public partial class SIWsResultArrayOfServiceInfoRecord
    {
        
        private ServiceInfoRecord[] resultsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public ServiceInfoRecord[] Results
        {
            get
            {
                return this.resultsField;
            }
            set
            {
                this.resultsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
    public partial class SIWsOutputOfSIWsResultArrayOfServiceInfoRecord
    {
        
        private SIWsStatus serviceStatusField;
        
        private SIWsResultArrayOfServiceInfoRecord serviceResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SIWsStatus ServiceStatus
        {
            get
            {
                return this.serviceStatusField;
            }
            set
            {
                this.serviceStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SIWsResultArrayOfServiceInfoRecord ServiceResult
        {
            get
            {
                return this.serviceResultField;
            }
            set
            {
                this.serviceResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
    public partial class SIWsStatus
    {
        
        private int statusNbrField;
        
        private string statusDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int StatusNbr
        {
            get
            {
                return this.statusNbrField;
            }
            set
            {
                this.statusNbrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusDescription
        {
            get
            {
                return this.statusDescriptionField;
            }
            set
            {
                this.statusDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
    public partial class SIWsResultArrayOfMethodStatusRecord
    {
        
        private MethodStatusRecord[] resultsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public MethodStatusRecord[] Results
        {
            get
            {
                return this.resultsField;
            }
            set
            {
                this.resultsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
    public partial class MethodStatusRecord : SIWsResultArrayOfSIWsStatus
    {
        
        private string methodNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MethodName
        {
            get
            {
                return this.methodNameField;
            }
            set
            {
                this.methodNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MethodStatusRecord))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
    public partial class SIWsResultArrayOfSIWsStatus
    {
        
        private SIWsStatus[] resultsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public SIWsStatus[] Results
        {
            get
            {
                return this.resultsField;
            }
            set
            {
                this.resultsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
    public partial class SIWsOutputOfSIWsResultArrayOfMethodStatusRecord
    {
        
        private SIWsStatus serviceStatusField;
        
        private SIWsResultArrayOfMethodStatusRecord serviceResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SIWsStatus ServiceStatus
        {
            get
            {
                return this.serviceStatusField;
            }
            set
            {
                this.serviceStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SIWsResultArrayOfMethodStatusRecord ServiceResult
        {
            get
            {
                return this.serviceResultField;
            }
            set
            {
                this.serviceResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
    public partial class SIWsOutputOfMethodStatusRecord
    {
        
        private SIWsStatus serviceStatusField;
        
        private MethodStatusRecord serviceResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SIWsStatus ServiceStatus
        {
            get
            {
                return this.serviceStatusField;
            }
            set
            {
                this.serviceStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public MethodStatusRecord ServiceResult
        {
            get
            {
                return this.serviceResultField;
            }
            set
            {
                this.serviceResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
    public partial class TaxRateCanadaData
    {
        
        private string abbreviationField;
        
        private string provinceField;
        
        private double gSTField;
        
        private double pSTField;
        
        private double totalField;
        
        private string taxShippingHandlingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Abbreviation
        {
            get
            {
                return this.abbreviationField;
            }
            set
            {
                this.abbreviationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Province
        {
            get
            {
                return this.provinceField;
            }
            set
            {
                this.provinceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double GST
        {
            get
            {
                return this.gSTField;
            }
            set
            {
                this.gSTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double PST
        {
            get
            {
                return this.pSTField;
            }
            set
            {
                this.pSTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double Total
        {
            get
            {
                return this.totalField;
            }
            set
            {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string TaxShippingHandling
        {
            get
            {
                return this.taxShippingHandlingField;
            }
            set
            {
                this.taxShippingHandlingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
    public partial class SIWsOutputOfTaxRateCanadaData
    {
        
        private SIWsStatus serviceStatusField;
        
        private TaxRateCanadaData serviceResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SIWsStatus ServiceStatus
        {
            get
            {
                return this.serviceStatusField;
            }
            set
            {
                this.serviceStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TaxRateCanadaData ServiceResult
        {
            get
            {
                return this.serviceResultField;
            }
            set
            {
                this.serviceResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.strikeiron.com")]
    public partial class SubscriptionInfo
    {
        
        private int licenseStatusCodeField;
        
        private string licenseStatusField;
        
        private int licenseActionCodeField;
        
        private string licenseActionField;
        
        private int remainingHitsField;
        
        private decimal amountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int LicenseStatusCode
        {
            get
            {
                return this.licenseStatusCodeField;
            }
            set
            {
                this.licenseStatusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LicenseStatus
        {
            get
            {
                return this.licenseStatusField;
            }
            set
            {
                this.licenseStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int LicenseActionCode
        {
            get
            {
                return this.licenseActionCodeField;
            }
            set
            {
                this.licenseActionCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string LicenseAction
        {
            get
            {
                return this.licenseActionField;
            }
            set
            {
                this.licenseActionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int RemainingHits
        {
            get
            {
                return this.remainingHitsField;
            }
            set
            {
                this.remainingHitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.strikeiron.com")]
    public partial class RegisteredUser
    {
        
        private string userIDField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
    public partial class TaxRateUSAData
    {
        
        private string zIPCodeField;
        
        private string stateField;
        
        private string countyField;
        
        private string cityField;
        
        private double stateSalesTaxField;
        
        private double stateUseTaxField;
        
        private double countySalesTaxField;
        
        private double countyUseTaxField;
        
        private double citySalesTaxField;
        
        private double cityUseTaxField;
        
        private double totalSalesTaxField;
        
        private double totalUseTaxField;
        
        private string taxShippingAloneField;
        
        private string taxShippingHandlingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ZIPCode
        {
            get
            {
                return this.zIPCodeField;
            }
            set
            {
                this.zIPCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string County
        {
            get
            {
                return this.countyField;
            }
            set
            {
                this.countyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double StateSalesTax
        {
            get
            {
                return this.stateSalesTaxField;
            }
            set
            {
                this.stateSalesTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public double StateUseTax
        {
            get
            {
                return this.stateUseTaxField;
            }
            set
            {
                this.stateUseTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double CountySalesTax
        {
            get
            {
                return this.countySalesTaxField;
            }
            set
            {
                this.countySalesTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public double CountyUseTax
        {
            get
            {
                return this.countyUseTaxField;
            }
            set
            {
                this.countyUseTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public double CitySalesTax
        {
            get
            {
                return this.citySalesTaxField;
            }
            set
            {
                this.citySalesTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public double CityUseTax
        {
            get
            {
                return this.cityUseTaxField;
            }
            set
            {
                this.cityUseTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public double TotalSalesTax
        {
            get
            {
                return this.totalSalesTaxField;
            }
            set
            {
                this.totalSalesTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public double TotalUseTax
        {
            get
            {
                return this.totalUseTaxField;
            }
            set
            {
                this.totalUseTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string TaxShippingAlone
        {
            get
            {
                return this.taxShippingAloneField;
            }
            set
            {
                this.taxShippingAloneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string TaxShippingHandling
        {
            get
            {
                return this.taxShippingHandlingField;
            }
            set
            {
                this.taxShippingHandlingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
    public partial class SIWsOutputOfTaxRateUSAData
    {
        
        private SIWsStatus serviceStatusField;
        
        private TaxRateUSAData serviceResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SIWsStatus ServiceStatus
        {
            get
            {
                return this.serviceStatusField;
            }
            set
            {
                this.serviceStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TaxRateUSAData ServiceResult
        {
            get
            {
                return this.serviceResultField;
            }
            set
            {
                this.serviceResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTaxRateUS", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
    public partial class GetTaxRateUSRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.strikeiron.com")]
        public TaxDataBasic.LicenseInfo LicenseInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
        public string ZIPCode;
        
        public GetTaxRateUSRequest()
        {
        }
        
        public GetTaxRateUSRequest(TaxDataBasic.LicenseInfo LicenseInfo, string ZIPCode)
        {
            this.LicenseInfo = LicenseInfo;
            this.ZIPCode = ZIPCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTaxRateUSResponse", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
    public partial class GetTaxRateUSResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.strikeiron.com")]
        public TaxDataBasic.SubscriptionInfo SubscriptionInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
        public TaxDataBasic.SIWsOutputOfTaxRateUSAData GetTaxRateUSResult;
        
        public GetTaxRateUSResponse()
        {
        }
        
        public GetTaxRateUSResponse(TaxDataBasic.SubscriptionInfo SubscriptionInfo, TaxDataBasic.SIWsOutputOfTaxRateUSAData GetTaxRateUSResult)
        {
            this.SubscriptionInfo = SubscriptionInfo;
            this.GetTaxRateUSResult = GetTaxRateUSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTaxRateCanada", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
    public partial class GetTaxRateCanadaRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.strikeiron.com")]
        public TaxDataBasic.LicenseInfo LicenseInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
        public string Province;
        
        public GetTaxRateCanadaRequest()
        {
        }
        
        public GetTaxRateCanadaRequest(TaxDataBasic.LicenseInfo LicenseInfo, string Province)
        {
            this.LicenseInfo = LicenseInfo;
            this.Province = Province;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTaxRateCanadaResponse", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
    public partial class GetTaxRateCanadaResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.strikeiron.com")]
        public TaxDataBasic.SubscriptionInfo SubscriptionInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
        public TaxDataBasic.SIWsOutputOfTaxRateCanadaData GetTaxRateCanadaResult;
        
        public GetTaxRateCanadaResponse()
        {
        }
        
        public GetTaxRateCanadaResponse(TaxDataBasic.SubscriptionInfo SubscriptionInfo, TaxDataBasic.SIWsOutputOfTaxRateCanadaData GetTaxRateCanadaResult)
        {
            this.SubscriptionInfo = SubscriptionInfo;
            this.GetTaxRateCanadaResult = GetTaxRateCanadaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStatusCodesForMethod", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
    public partial class GetStatusCodesForMethodRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.strikeiron.com")]
        public TaxDataBasic.LicenseInfo LicenseInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
        public string MethodName;
        
        public GetStatusCodesForMethodRequest()
        {
        }
        
        public GetStatusCodesForMethodRequest(TaxDataBasic.LicenseInfo LicenseInfo, string MethodName)
        {
            this.LicenseInfo = LicenseInfo;
            this.MethodName = MethodName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStatusCodesForMethodResponse", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
    public partial class GetStatusCodesForMethodResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.strikeiron.com")]
        public TaxDataBasic.SubscriptionInfo SubscriptionInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
        public TaxDataBasic.SIWsOutputOfMethodStatusRecord GetStatusCodesForMethodResult;
        
        public GetStatusCodesForMethodResponse()
        {
        }
        
        public GetStatusCodesForMethodResponse(TaxDataBasic.SubscriptionInfo SubscriptionInfo, TaxDataBasic.SIWsOutputOfMethodStatusRecord GetStatusCodesForMethodResult)
        {
            this.SubscriptionInfo = SubscriptionInfo;
            this.GetStatusCodesForMethodResult = GetStatusCodesForMethodResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStatusCodes", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
    public partial class GetStatusCodesRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.strikeiron.com")]
        public TaxDataBasic.LicenseInfo LicenseInfo;
        
        public GetStatusCodesRequest()
        {
        }
        
        public GetStatusCodesRequest(TaxDataBasic.LicenseInfo LicenseInfo)
        {
            this.LicenseInfo = LicenseInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStatusCodesResponse", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
    public partial class GetStatusCodesResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.strikeiron.com")]
        public TaxDataBasic.SubscriptionInfo SubscriptionInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
        public TaxDataBasic.SIWsOutputOfSIWsResultArrayOfMethodStatusRecord GetStatusCodesResult;
        
        public GetStatusCodesResponse()
        {
        }
        
        public GetStatusCodesResponse(TaxDataBasic.SubscriptionInfo SubscriptionInfo, TaxDataBasic.SIWsOutputOfSIWsResultArrayOfMethodStatusRecord GetStatusCodesResult)
        {
            this.SubscriptionInfo = SubscriptionInfo;
            this.GetStatusCodesResult = GetStatusCodesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetServiceInfo", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
    public partial class GetServiceInfoRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.strikeiron.com")]
        public TaxDataBasic.LicenseInfo LicenseInfo;
        
        public GetServiceInfoRequest()
        {
        }
        
        public GetServiceInfoRequest(TaxDataBasic.LicenseInfo LicenseInfo)
        {
            this.LicenseInfo = LicenseInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetServiceInfoResponse", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
    public partial class GetServiceInfoResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.strikeiron.com")]
        public TaxDataBasic.SubscriptionInfo SubscriptionInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
        public TaxDataBasic.SIWsOutputOfSIWsResultArrayOfServiceInfoRecord GetServiceInfoResult;
        
        public GetServiceInfoResponse()
        {
        }
        
        public GetServiceInfoResponse(TaxDataBasic.SubscriptionInfo SubscriptionInfo, TaxDataBasic.SIWsOutputOfSIWsResultArrayOfServiceInfoRecord GetServiceInfoResult)
        {
            this.SubscriptionInfo = SubscriptionInfo;
            this.GetServiceInfoResult = GetServiceInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRemainingHits", WrapperNamespace="http://ws.strikeiron.com", IsWrapped=true)]
    public partial class GetRemainingHitsRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.strikeiron.com")]
        public TaxDataBasic.LicenseInfo LicenseInfo;
        
        public GetRemainingHitsRequest()
        {
        }
        
        public GetRemainingHitsRequest(TaxDataBasic.LicenseInfo LicenseInfo)
        {
            this.LicenseInfo = LicenseInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRemainingHitsResponse", WrapperNamespace="http://ws.strikeiron.com", IsWrapped=true)]
    public partial class GetRemainingHitsResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.strikeiron.com")]
        public TaxDataBasic.SubscriptionInfo SubscriptionInfo;
        
        public GetRemainingHitsResponse()
        {
        }
        
        public GetRemainingHitsResponse(TaxDataBasic.SubscriptionInfo SubscriptionInfo)
        {
            this.SubscriptionInfo = SubscriptionInfo;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface TaxDataBasicSoapChannel : TaxDataBasic.TaxDataBasicSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class TaxDataBasicSoapClient : System.ServiceModel.ClientBase<TaxDataBasic.TaxDataBasicSoap>, TaxDataBasic.TaxDataBasicSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TaxDataBasicSoapClient() : 
                base(TaxDataBasicSoapClient.GetDefaultBinding(), TaxDataBasicSoapClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.TaxDataBasicSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TaxDataBasicSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(TaxDataBasicSoapClient.GetBindingForEndpoint(endpointConfiguration), TaxDataBasicSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TaxDataBasicSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TaxDataBasicSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TaxDataBasicSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TaxDataBasicSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TaxDataBasicSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TaxDataBasic.GetTaxRateUSResponse> TaxDataBasic.TaxDataBasicSoap.GetTaxRateUSAsync(TaxDataBasic.GetTaxRateUSRequest request)
        {
            return base.Channel.GetTaxRateUSAsync(request);
        }
        
        public System.Threading.Tasks.Task<TaxDataBasic.GetTaxRateUSResponse> GetTaxRateUSAsync(TaxDataBasic.LicenseInfo LicenseInfo, string ZIPCode)
        {
            TaxDataBasic.GetTaxRateUSRequest inValue = new TaxDataBasic.GetTaxRateUSRequest();
            inValue.LicenseInfo = LicenseInfo;
            inValue.ZIPCode = ZIPCode;
            return ((TaxDataBasic.TaxDataBasicSoap)(this)).GetTaxRateUSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TaxDataBasic.GetTaxRateCanadaResponse> TaxDataBasic.TaxDataBasicSoap.GetTaxRateCanadaAsync(TaxDataBasic.GetTaxRateCanadaRequest request)
        {
            return base.Channel.GetTaxRateCanadaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TaxDataBasic.GetTaxRateCanadaResponse> GetTaxRateCanadaAsync(TaxDataBasic.LicenseInfo LicenseInfo, string Province)
        {
            TaxDataBasic.GetTaxRateCanadaRequest inValue = new TaxDataBasic.GetTaxRateCanadaRequest();
            inValue.LicenseInfo = LicenseInfo;
            inValue.Province = Province;
            return ((TaxDataBasic.TaxDataBasicSoap)(this)).GetTaxRateCanadaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TaxDataBasic.GetStatusCodesForMethodResponse> TaxDataBasic.TaxDataBasicSoap.GetStatusCodesForMethodAsync(TaxDataBasic.GetStatusCodesForMethodRequest request)
        {
            return base.Channel.GetStatusCodesForMethodAsync(request);
        }
        
        public System.Threading.Tasks.Task<TaxDataBasic.GetStatusCodesForMethodResponse> GetStatusCodesForMethodAsync(TaxDataBasic.LicenseInfo LicenseInfo, string MethodName)
        {
            TaxDataBasic.GetStatusCodesForMethodRequest inValue = new TaxDataBasic.GetStatusCodesForMethodRequest();
            inValue.LicenseInfo = LicenseInfo;
            inValue.MethodName = MethodName;
            return ((TaxDataBasic.TaxDataBasicSoap)(this)).GetStatusCodesForMethodAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TaxDataBasic.GetStatusCodesResponse> TaxDataBasic.TaxDataBasicSoap.GetStatusCodesAsync(TaxDataBasic.GetStatusCodesRequest request)
        {
            return base.Channel.GetStatusCodesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TaxDataBasic.GetStatusCodesResponse> GetStatusCodesAsync(TaxDataBasic.LicenseInfo LicenseInfo)
        {
            TaxDataBasic.GetStatusCodesRequest inValue = new TaxDataBasic.GetStatusCodesRequest();
            inValue.LicenseInfo = LicenseInfo;
            return ((TaxDataBasic.TaxDataBasicSoap)(this)).GetStatusCodesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TaxDataBasic.GetServiceInfoResponse> TaxDataBasic.TaxDataBasicSoap.GetServiceInfoAsync(TaxDataBasic.GetServiceInfoRequest request)
        {
            return base.Channel.GetServiceInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TaxDataBasic.GetServiceInfoResponse> GetServiceInfoAsync(TaxDataBasic.LicenseInfo LicenseInfo)
        {
            TaxDataBasic.GetServiceInfoRequest inValue = new TaxDataBasic.GetServiceInfoRequest();
            inValue.LicenseInfo = LicenseInfo;
            return ((TaxDataBasic.TaxDataBasicSoap)(this)).GetServiceInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TaxDataBasic.GetRemainingHitsResponse> TaxDataBasic.TaxDataBasicSoap.GetRemainingHitsAsync(TaxDataBasic.GetRemainingHitsRequest request)
        {
            return base.Channel.GetRemainingHitsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TaxDataBasic.GetRemainingHitsResponse> GetRemainingHitsAsync(TaxDataBasic.LicenseInfo LicenseInfo)
        {
            TaxDataBasic.GetRemainingHitsRequest inValue = new TaxDataBasic.GetRemainingHitsRequest();
            inValue.LicenseInfo = LicenseInfo;
            return ((TaxDataBasic.TaxDataBasicSoap)(this)).GetRemainingHitsAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TaxDataBasicSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TaxDataBasicSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://ws.strikeiron.com/StrikeIron/TaxDataBasic5/TaxDataBasic");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TaxDataBasicSoapClient.GetBindingForEndpoint(EndpointConfiguration.TaxDataBasicSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TaxDataBasicSoapClient.GetEndpointAddress(EndpointConfiguration.TaxDataBasicSoap);
        }
        
        public enum EndpointConfiguration
        {
            
            TaxDataBasicSoap,
        }
    }
}
